### ISSUE TITLE
Where can I find the checkin box?

### ISSUE THREAD

**Issue by cuteSakuraHime** [mudkipme/nodebb-plugin-checkin#1]
Hello,

After active, I can’t find anywhere to checkin.

**Comment by cuteSakuraHime** [comment]
```
2018-07-01T10:00:19.288Z [498] - error: /root/nodebb-bak/node_modules/nodebb-plugin-checkin/library.js:43
        const render = async function (req, res, next) {
                             ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.Plugins.requireLibrary (/root/nodebb-bak/src/plugins.js:44:32)
    at registerHooks (/root/nodebb-bak/src/plugins/load.js:180:13)
    at /root/nodebb-bak/src/plugins/load.js:138:6
    at /root/nodebb-bak/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/root/nodebb-bak/node_modules/async/dist/async.js:1055:9)
    at eachOf (/root/nodebb-bak/node_modules/async/dist/async.js:1103:5)
    at _parallel (/root/nodebb-bak/node_modules/async/dist/async.js:3865:5)
2018-07-01T10:00:19.288Z [498] - warn: [plugins] Unable to parse library for: nodebb-plugin-checkin
```

Here is the erroe code from console.

The NodeBB version is v1.9.3 and using redis as database.

**Comment by mudkipme** [comment]
This plugin requires Node.js 8 or later. You may also manually compile `library.js` to a JavaScript version earlier than ES2017 with Babel.

After installation, the checkin button can be dragged to navigation.

**Comment by cuteSakuraHime** [comment]
Hello,

It works when I updated nodejs version and rebuilt.

Thank you for your help!

Cheers.
