### ISSUE TITLE
Change "module.parent.require" to "require.main.require"?

### ISSUE THREAD

**Issue by PatheticMustan** [mudkipme/nodebb-plugin-checkin#3]
```
2019-05-31T14:31:23.960Z [4567/30019] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:4:28)
2019-05-31T14:31:23.961Z [4567/30019] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:5:26)
2019-05-31T14:31:23.962Z [4567/30019] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./notifications')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:6:37)
2019-05-31T14:31:23.963Z [4567/30019] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./routes/helpers')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:7:36)
2019-05-31T14:31:23.963Z [4567/30019] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./controllers/helpers')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:8:41)
```

**Comment by PatheticMustan** [comment]
Oops, wrong issue, I always meant #4
